vim.opt.colorcolumn = "80"
vim.opt.updatetime = 50
vim.opt.swapfile = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.backup = false
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.termguicolors = true
vim.opt.go="a"
vim.opt.mouse="a"
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.showmode = false
vim.opt.ruler = false
vim.opt.clipboard = "unnamedplus"               -- allows neovim to access the system clipboard
vim.opt.showcmd = false                         -- hide (partial) command in the last line of the screen (for performance)
vim.opt.laststatus = 3                          -- only the last window will always have a status line
vim.opt.compatible = false
vim.opt.encoding="utf-8"
vim.opt.wildmode="longest,list,full"
vim.opt.splitbelow = true                       -- force all horizontal splits to go below current window
vim.opt.splitright = true                       -- force all vertical splits to go to the right of current window
vim.opt.scrolloff = 8
vim.g.mapleader = ","
